name: Build
on:
  workflow_dispatch:
  release:
    types: [published]

env:
  IMAGE_NAME: andreibegu/tarkov-item-bot

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Login to Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Check out
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t ${IMAGE_NAME}:${GITHUB_REF#refs/tags/v} .

      - name: Publish image
        run: docker push --all-tags ${IMAGE_NAME}

      - name: Logout
        run: docker logout 

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    env:
      GCE_INSTANCE: tarkov-item-bot
      GCE_INSTANCE_ZONE: europe-west1-b
    steps:

      - name: Set up config
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCE_SA_KEY }}
          project_id: ${{ secrets.GCE_PROJECT }}

      - name: Deploy image
        run: | 
          gcloud compute instances update-container "$GCE_INSTANCE" \
          --zone "$GCE_INSTANCE_ZONE" \
          --container-image "${IMAGE_NAME}:${GITHUB_REF#refs/tags/v}"

      - name: Logout
        run: gcloud auth revoke
